// Generated by build/desktop-core.cjs. Edit src/core instead.
export function createCore({ request, storage = new Map() }) {
const GM_xmlhttpRequest = request;
const GM_getValue = (key, fallback) => storage.has(key) ? storage.get(key) : fallback;
const GM_setValue = (key, value) => storage.set(key, value);
const stateModule = (() => {
/**
 * Shared state management for SegmentScraper
 * Manages captured timestamps, UI state, and deduplication cache
 */

/**
 * Create a cache key for an episode
 * @param {string} imdbId - IMDb ID (e.g., 'tt1234567')
 * @param {string|number} season - Season number
 * @param {string|number} episode - Episode number
 * @returns {string} - Cache key in format 'imdbId|season|episode'
 */
function createEpisodeCacheKey(imdbId, season, episode) {
  return `${String(imdbId)}|${String(season)}|${String(episode)}`;
}

/**
 * Create a cache key for either a TV episode or a movie.
 * Movies intentionally omit season/episode because they do not use TVDB.
 */
function createMediaCacheKey(imdbId, mediaType = 'tv', season, episode) {
  return String(mediaType).toLowerCase() === 'movie'
    ? `${String(imdbId)}|movie`
    : createEpisodeCacheKey(imdbId, season, episode);
}

/**
 * Create a cache key for a segment (includes segment type)
 * @param {string} imdbId - IMDb ID
 * @param {string|number} season - Season number
 * @param {string|number} episode - Episode number
 * @param {string} segmentType - Segment type (intro, recap, outro)
 * @returns {string} - Cache key in format 'imdbId|season|episode|segment_type'
 */
function createSegmentCacheKey(imdbId, season, episode, segmentType) {
  return `${String(imdbId)}|${String(season)}|${String(episode)}|${segmentType}`;
}

const createState = (providerName) => ({
  allItems: [],
  imdbId: '',
  dbSearchDone: false,
  dbStatusMsg: `Waiting for ${providerName} metadata...`,
  showTitle: '',
  mediaType: 'tv',
  showId: null,
  showYear: '',
  showIds: new Set(),
  imdbIdsByShowId: {},
  interceptedCount: 0,
  panelVisible: false,
  submitInProgress: false,
  exportInProgress: false,
  sessionSavedAt: '',
  sessionStorageError: false,
  submitResults: { ok: 0, fail: 0 },
  dedupCacheV2: {},
  introdbApiKey: '',
  tvdbApiKey: '',
  tvdbPin: '',
  providerEpisodes: [],
  providerEpisodesByShowId: {},
  updateStatus: 'idle',
  updateRequired: false,
  currentVersion: '',
  latestVersion: '',
  updateUrl: '',
});

const state = createState('Streaming Service');

return { createEpisodeCacheKey, createMediaCacheKey, createSegmentCacheKey, createState, state };
})();
const { state, createMediaCacheKey } = stateModule;
const output_policy = (() => {
/** Shared wire format and timing rules for both clients. Client-specific scene policy stays explicit. */
function capturedSegmentKey(item) {
  return JSON.stringify([String(item._showId || ''), String(item._eid), item.season, item.episode, item.segment_type, Number(item.start_sec), Number(item.end_sec)]);
}
function outputSegmentAllowed(item) {
  const movie=item?.is_movie===true||String(item?.media_type||item?.mediaType||item?._mediaType||'').toLowerCase()==='movie';
  const start=Number(item?.start_sec),end=Number(item?.end_sec);
  return Number.isFinite(start)&&Number.isFinite(end)&&start>=0&&end-start>=5&&(!movie||(['outro','post-credits'].includes(item.segment_type)&&end-start<=(item.segment_type==='outro'?900:600)));
}
function introdbPayload(item) {
  const movie=item?.is_movie===true||String(item?.media_type||item?.mediaType||item?._mediaType||'').toLowerCase()==='movie';
  return {imdb_id:item.imdb_id,segment_type:item.segment_type,start_sec:item.start_sec,end_sec:item.end_sec,...(movie?{is_movie:true}:{season:item.season,episode:item.episode})};
}

return { capturedSegmentKey, outputSegmentAllowed, introdbPayload };
})();
const { outputSegmentAllowed, introdbPayload } = output_policy;
const network = (() => {
/**
 * Shared network utilities for SegmentScraper
 * Handles API requests, IMDb lookups, and IntroDB integration
 */


const INTRODB_BASE = 'https://api.introdb.app';

/**
 * Get GM_xmlhttpRequest if available (Tampermonkey/Greasemonkey)
 */
function getGmXhr() {
  return (typeof GM_xmlhttpRequest !== 'undefined' ? GM_xmlhttpRequest : null) ||
         (typeof _GM_xmlhttpRequest !== 'undefined' ? _GM_xmlhttpRequest : null) ||
         (typeof GM !== 'undefined' && GM.xmlHttpRequest ? GM.xmlHttpRequest : null);
}

function filterImdbTitleResults(results, mediaType = 'tv') {
  const movieQids = new Set(['movie', 'tvmovie', 'videomovie', 'featurefilm', 'film', 'short', 'tvshort']);
  const allowedQids = String(mediaType).toLowerCase() === 'movie'
    ? movieQids
    : new Set(['tvseries', 'tvminiseries', 'tvshort', 'tvspecial']);
  return (results || []).filter(result => allowedQids.has(String(result?.qid || '').toLowerCase()));
}

function chooseImdbTitleResult(results, title, year) {
  const normalizedTitle = String(title || '').trim().toLowerCase();
  const normalizedYear = year == null ? '' : String(year);
  let best = results[0];
  if (normalizedYear) {
    const byYearAndTitle = results.find(result =>
      String(result?.y || '') === normalizedYear && String(result?.l || '').trim().toLowerCase() === normalizedTitle
    );
    const byYear = results.find(result => String(result?.y || '') === normalizedYear);
    if (byYearAndTitle) best = byYearAndTitle;
    else if (byYear) best = byYear;
  } else {
    const exact = results.find(result => String(result?.l || '').trim().toLowerCase() === normalizedTitle);
    if (exact) best = exact;
  }
  return best;
}

function resolveImdbSearchResponse(data, title, year, mediaType) {
  const results = filterImdbTitleResults(data?.d, mediaType);
  console.log(`[NFE] Filtered ${mediaType === 'movie' ? 'movie' : 'TV series'} results:`, results.length);
  if (!results.length) return { success: false, error: 'Not found on IMDb' };

  const best = chooseImdbTitleResult(results, title, year);
  const imdbId = best?.id;
  if (!imdbId || !String(imdbId).startsWith('tt')) {
    return { success: false, error: 'Could not obtain a valid IMDb ID' };
  }

  return {
    success: true,
    imdbId,
    title: best?.l || title,
    year: best?.y,
  };
}

/**
 * Search IMDb by title and return the best matching media ID.
 */
async function searchImdbByTitle(title, year, { mediaType = 'tv' } = {}) {
  const query = encodeURIComponent(String(title || '').toLowerCase().replace(/[^\p{L}\p{N} ]/gu, '').trim());
  const url = `https://v3.sg.media-imdb.com/suggestion/x/${query}.json`;
  console.log('[NFE] IMDb search request URL:', url, 'for title:', title, 'year:', year);

  const gmXhr = getGmXhr();
  console.log('[NFE] GM_xmlhttpRequest available:', !!gmXhr, 'using fetch fallback');
  if (gmXhr) {
    return new Promise((resolve) => {
      gmXhr({
        method: 'GET',
        url: url,
        timeout: 10000,
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36',
          'Accept': 'application/json',
          'Origin': 'https://www.netflix.com'
        },
        onload: (response) => {
          console.log('[NFE] IMDb search response status:', response.status, 'responseText length:', response.responseText?.length);
          try {
            const data = JSON.parse(response.responseText);
            console.log('[NFE] IMDb search response data:', data);
            resolve(resolveImdbSearchResponse(data, title, year, mediaType));
          } catch (parseError) {
            console.error('[NFE] IMDb response parse error:', parseError);
            resolve({ success: false, error: 'Failed to parse IMDb response' });
          }
        },
        onerror: (error) => {
          console.error('[NFE] IMDb search error details:', JSON.stringify(error, null, 2));
          resolve({ success: false, error: 'Network error connecting to IMDb: ' + (error?.error || error?.status || error?.message || JSON.stringify(error)) });
        },
        ontimeout: () => {
          console.error('[NFE] IMDb search timeout');
          resolve({ success: false, error: 'IMDb search timeout' });
        }
      });
    });
  }

  console.log('[NFE] Using fetch fallback (may fail due to CORS)');
  try {
    const response = await fetch(url, { signal: AbortSignal.timeout(15000) });
    const data = await response.json();
    console.log('[NFE] IMDb search response data:', data);
    return resolveImdbSearchResponse(data, title, year, mediaType);
  } catch (error) {
    console.error('[NFE] Fetch fallback error:', error);
    return { success: false, error: 'Network error connecting to IMDb (CORS or network issue)' };
  }
}

/**
 * Load existing segments from IntroDB for deduplication
 * Uses GM_xmlhttpRequest to avoid CORS issues
 *
 * This function collects unique episode keys from the currently captured items
 * and calls /segments endpoint once per unique episode.
 *
 * @param {string} imdbId - IMDb ID to load segments for
 * @param {string} apiKey - IntroDB API key (optional)
 * @returns {Promise<Array>} - Array of { key, segmentType } objects
 */
async function loadExistingSegments(imdbId, apiKey) {
  console.log('[NFE-DEDUP] loadExistingSegments called for imdbId:', imdbId);

  // Collect unique episode keys from currently captured items for this imdb_id
  const mediaKeys = [...new Set(
    state.allItems
      .filter(i => i.imdb_id === imdbId)
      .map(i => createMediaCacheKey(imdbId, i.media_type || i.mediaType || i._mediaType, i.season, i.episode))
  )];

  console.log('[NFE-DEDUP] loadExistingSegments: unique media keys collected:', mediaKeys);

  // Load each episode's segments via /segments endpoint
  const results = await Promise.all(
    mediaKeys.map(key => loadExistingSegmentsForEpisode(key, apiKey))
  );

  // Return all segment types found
  const allSegments = [];
  for (let i = 0; i < mediaKeys.length; i++) {
    const key = mediaKeys[i];
    const set = results[i];
    for (const segType of set) {
      allSegments.push({ key, segmentType: segType });
    }
  }

  console.log('[NFE-DEDUP] loadExistingSegments: total existing segments found:', allSegments.length);
  return allSegments;
}

/**
 * Load existing segments for a specific episode (for export deduplication)
 * Uses GM_xmlhttpRequest to avoid CORS issues
 */
async function loadExistingSegmentsForEpisode(key, apiKey, { useCache = true, writeCache = true } = {}) {
  if (useCache && state.dedupCacheV2[key]) {
    return state.dedupCacheV2[key];
  }
  
  const [imdbId, seasonOrMediaType, episode] = key.split('|');
  const isMovie = seasonOrMediaType === 'movie';
  if (!isMovie && (!/^\d+$/.test(seasonOrMediaType || '') || Number(seasonOrMediaType) < 1
    || !/^\d+$/.test(episode || '') || Number(episode) < 1)) {
    throw new Error(`IntroDB cannot check ${imdbId} S${seasonOrMediaType}E${episode}: season and episode must be positive integers.`);
  }
  const describeHttpError = (status, body) => {
    let detail = '';
    try { const json = JSON.parse(body); detail = typeof json.error === 'string' ? json.error.slice(0, 200) : ''; } catch (_) {}
    return new Error(`IntroDB duplicate check returned HTTP ${status} for ${imdbId} S${seasonOrMediaType}E${episode}${detail ? `: ${detail}` : '.'}`);
  };
  const url = isMovie
    ? `${INTRODB_BASE}/segments?imdb_id=${encodeURIComponent(imdbId)}&is_movie=true`
    : `${INTRODB_BASE}/segments?imdb_id=${encodeURIComponent(imdbId)}&season=${encodeURIComponent(seasonOrMediaType)}&episode=${encodeURIComponent(episode)}`;
  
  const gmXhr = getGmXhr();

  const parseExistingSegments = json => {
    if (!json || typeof json !== 'object' || json.error || json.errors) {
      throw new Error('IntroDB returned an invalid response. Please try again.');
    }
    const set = new Set();
    const rangesByType = new Map();
    const coerceExistingSeconds = value => {
      const number = Number(value);
      if (Number.isFinite(number)) return number;
      const parts = String(value || '').trim().split(':').map(Number);
      if (parts.length === 2 && parts.every(Number.isFinite)) return parts[0] * 60 + parts[1];
      if (parts.length === 3 && parts.every(Number.isFinite)) return parts[0] * 3600 + parts[1] * 60 + parts[2];
      return null;
    };
    const readRangeValue = (source, secondsKeys, millisecondsKey) => {
      for (const key of secondsKeys) {
        if (source?.[key] != null) return coerceExistingSeconds(source[key]);
      }
      if (source?.[millisecondsKey] != null) return Number(source[millisecondsKey]) / 1000;
      return null;
    };
    const add = (segmentType, value) => {
      const normalizedType = segmentType === 'credits' ? 'outro' : segmentType === 'post_credits' ? 'post-credits' : segmentType;
      if (!['intro', 'recap', 'outro', 'post-credits'].includes(normalizedType) || value == null) return;
      set.add(normalizedType);
      const entries = Array.isArray(value) ? value : [value];
      const ranges = entries.map(entry => {
        const source = entry?.segment && typeof entry.segment === 'object' ? entry.segment : entry;
        const start = readRangeValue(source, ['start_sec', 'startSec', 'start'], 'start_ms');
        const end = readRangeValue(source, ['end_sec', 'endSec', 'end'], 'end_ms');
        if (!Number.isFinite(start) || !Number.isFinite(end) || end <= start) return null;
        return {
          startSec: start,
          endSec: end,
          creditPart: source?.credit_part ?? source?.creditPart ?? null,
        };
      }).filter(Boolean);
      if (ranges.length) rangesByType.set(normalizedType, [...(rangesByType.get(normalizedType) || []), ...ranges]);
    };

    if (Array.isArray(json)) {
      json.forEach(entry => add(entry?.segment_type || entry?.segmentType, entry));
    } else if (Array.isArray(json?.segments)) {
      json.segments.forEach(entry => add(entry?.segment_type || entry?.segmentType, entry));
    }
    for (const type of ['intro', 'recap', 'outro', 'credits', 'post_credits', 'post-credits']) add(type, json?.[type]);
    Object.defineProperty(set, 'rangesByType', { value: rangesByType, enumerable: false });
    return set;
  };
  
  return new Promise((resolve, reject) => {
    if (gmXhr) {
      gmXhr({
        method: 'GET',
        url: url,
        timeout: 15000,
        ontimeout: () => reject(new Error('IntroDB duplicate check timed out. Please try again.')),
        onabort: () => reject(new Error('IntroDB duplicate check was interrupted. Please try again.')),
        headers: { 'Accept': 'application/json' },
        onload: (response) => {
          try {
            if (response.status === 200) {
              const json = JSON.parse(response.responseText);
              const set = parseExistingSegments(json);
              if (writeCache) state.dedupCacheV2[key] = set;
              resolve(set);
            } else if (response.status === 404) {
              if (writeCache) state.dedupCacheV2[key] = new Set();
              resolve(new Set());
            } else {
              reject(describeHttpError(response.status, response.responseText));
            }
          } catch (_) {
            reject(new Error('IntroDB returned an invalid response. Please try again.'));
          }
        },
        onerror: () => {
          reject(new Error('IntroDB duplicate check failed. Please try again.'));
        }
      });
    } else {
      // Fallback to fetch (will likely fail due to CORS)
      fetch(url, { signal: AbortSignal.timeout(15000) })
        .then(async response => {
          if (response.status === 404) return {};
          if (!response.ok) throw describeHttpError(response.status, await response.text());
          return response.json();
        })
        .then(json => {
          const set = parseExistingSegments(json);
          if (writeCache) state.dedupCacheV2[key] = set;
          resolve(set);
        })
        .catch(reject);
    }
  });
}

/**
 * Submit a single segment to IntroDB
 * Uses GM_xmlhttpRequest to avoid CORS issues
 */
async function submitSegment(item, apiKey) {
  const url = `${INTRODB_BASE}/submit`;
  const gmXhr = getGmXhr();
  const data = introdbPayload(item);
  
  if (gmXhr) {
    return new Promise((resolve) => {
      gmXhr({
        method: 'POST',
        url: url,
        timeout: 15000,
        ontimeout: () => resolve({ success: false, status: 0 }),
        onabort: () => resolve({ success: false, status: 0 }),
        headers: {
          'Content-Type': 'application/json',
          'X-API-Key': apiKey,
        },
        data: JSON.stringify(data),
        onload: (response) => {
          resolve({
            success: response.status >= 200 && response.status < 300,
            status: response.status
          });
        },
        onerror: () => {
          resolve({ success: false, status: 0 });
        }
      });
    });
  }

  // Fallback to fetch
  try {
    const response = await fetch(url, {
      method: 'POST',
      signal: AbortSignal.timeout(15000),
      headers: {
        'Content-Type': 'application/json',
        'X-API-Key': apiKey,
      },
      body: JSON.stringify(data),
    });

    return {
      success: response.status >= 200 && response.status < 300,
      status: response.status
    };
  } catch (error) {
    return { success: false, status: 0 };
  }
}

/**
 * Look up the display title for a known IMDb title ID.
 */
async function lookupImdbTitle(imdbId) {
  const url = `https://v3.sg.media-imdb.com/suggestion/x/${encodeURIComponent(imdbId)}.json`;
  const gmXhr = getGmXhr();

  try {
    const responseText = gmXhr
      ? await new Promise((resolve, reject) => {
          gmXhr({
            method: 'GET',
            url,
            timeout: 10000,
            headers: { Accept: 'application/json' },
            onload: response => resolve(response.responseText),
            onerror: reject,
            ontimeout: reject,
          });
        })
      : await fetch(url, { signal: AbortSignal.timeout(15000) }).then(response => response.text());
    const result = (JSON.parse(responseText).d || []).find(item => item.id === imdbId);
    return result ? { success: true, title: result.l, year: result.y } : { success: false };
  } catch (_) {
    return { success: false };
  }
}

return { searchImdbByTitle, loadExistingSegments, loadExistingSegmentsForEpisode, submitSegment, lookupImdbTitle };
})();
const tvdb = (() => {
/** TVDB v4 authentication, local settings, and conservative episode mapping. */


const TVDB_BASE = 'https://api4.thetvdb.com/v4';
const TVDB_STORAGE = {
  apiKey: 'segmentScraper.tvdb.apikey',
  pin: 'segmentScraper.tvdb.pin',
  token: 'segmentScraper.tvdb.token',
  tokenCreatedAt: 'segmentScraper.tvdb.tokenCreatedAt',
};
const TOKEN_MAX_AGE_MS = 29 * 24 * 60 * 60 * 1000;
const TVDB_EPISODE_LANGUAGE = 'eng';
const TVDB_SEASON_TYPE = 'default';
const GTST_IMDB_ID = 'tt0096597';
const TVDB_EPISODE_ENDPOINT_SHAPE = `${TVDB_BASE}/series/{seriesId}/episodes/{seasonType}/{language}?page={page}`;
let loginPromise = null;
const episodeListCache = new Map();
const episodeBaseCache = new Map();
const episodeTranslationCache = new Map();
const seriesExtendedCache = new Map();

function getStoredValue(key, fallback = '') {
  try {
    return typeof GM_getValue === 'function' ? GM_getValue(key, fallback) : fallback;
  } catch (_) {
    return fallback;
  }
}

function setStoredValue(key, value) {
  try {
    if (typeof GM_setValue === 'function') GM_setValue(key, value);
  } catch (_) {}
}

function getGmXhr() {
  return (typeof GM_xmlhttpRequest !== 'undefined' ? GM_xmlhttpRequest : null) ||
    (typeof _GM_xmlhttpRequest !== 'undefined' ? _GM_xmlhttpRequest : null) ||
    (typeof GM !== 'undefined' && GM.xmlHttpRequest ? GM.xmlHttpRequest : null);
}

function tvdbRequest({ method = 'GET', path, token = '', data }) {
  const url = `${TVDB_BASE}${path}`;
  const headers = { Accept: 'application/json' };
  if (data !== undefined) headers['Content-Type'] = 'application/json';
  if (token) headers.Authorization = `Bearer ${token}`;
  const gmXhr = getGmXhr();

  if (gmXhr) {
    return new Promise((resolve, reject) => {
      gmXhr({
        method,
        url,
        headers,
        data: data === undefined ? undefined : JSON.stringify(data),
        timeout: 15000,
        onload: response => {
          let body = null;
          try { body = response.responseText ? JSON.parse(response.responseText) : null; } catch (_) {}
          resolve({ status: response.status, body });
        },
        onerror: () => reject(new Error('TVDB network request failed')),
        ontimeout: () => reject(new Error('TVDB network request timed out')),
      });
    });
  }

  return fetch(url, {
    signal: AbortSignal.timeout(15000),
    method,
    headers,
    body: data === undefined ? undefined : JSON.stringify(data),
  }).then(async response => {
    let body = null;
    try { body = await response.json(); } catch (_) {}
    return { status: response.status, body };
  });
}

function loadTvdbSettings() {
  state.tvdbApiKey = String(getStoredValue(TVDB_STORAGE.apiKey, '') || '');
  state.tvdbPin = String(getStoredValue(TVDB_STORAGE.pin, '') || '');
  return { apiKey: state.tvdbApiKey, pin: state.tvdbPin };
}

function saveTvdbSettings(apiKey, pin = '') {
  const nextApiKey = String(apiKey || '').trim();
  const nextPin = String(pin || '').trim();
  const credentialsChanged = nextApiKey !== state.tvdbApiKey || nextPin !== state.tvdbPin;
  state.tvdbApiKey = nextApiKey;
  state.tvdbPin = nextPin;
  setStoredValue(TVDB_STORAGE.apiKey, nextApiKey);
  setStoredValue(TVDB_STORAGE.pin, nextPin);
  if (credentialsChanged) clearTvdbToken();
}

function clearTvdbToken() {
  setStoredValue(TVDB_STORAGE.token, '');
  setStoredValue(TVDB_STORAGE.tokenCreatedAt, 0);
}

async function loginTvdb() {
  if (!state.tvdbApiKey) throw new Error('No TVDB API key configured');
  const credentials = { apikey: state.tvdbApiKey };
  if (state.tvdbPin) credentials.pin = state.tvdbPin;
  const response = await tvdbRequest({ method: 'POST', path: '/login', data: credentials });
  const token = response.body?.data?.token;
  if (response.status < 200 || response.status >= 300 || !token) {
    throw new Error(`TVDB login failed (HTTP ${response.status || 0})`);
  }
  setStoredValue(TVDB_STORAGE.token, token);
  setStoredValue(TVDB_STORAGE.tokenCreatedAt, Date.now());
  return token;
}

async function getTvdbToken(forceRefresh = false) {
  const token = String(getStoredValue(TVDB_STORAGE.token, '') || '');
  const createdAt = Number(getStoredValue(TVDB_STORAGE.tokenCreatedAt, 0)) || 0;
  if (!forceRefresh && token && createdAt && Date.now() - createdAt < TOKEN_MAX_AGE_MS) return token;
  if (!loginPromise) loginPromise = loginTvdb().finally(() => { loginPromise = null; });
  return loginPromise;
}

async function authenticatedTvdbGet(path, includeEnvelope = false) {
  let token = await getTvdbToken(false);
  let response = await tvdbRequest({ path, token });
  if (response.status === 401) {
    clearTvdbToken();
    token = await getTvdbToken(true);
    response = await tvdbRequest({ path, token });
  }
  if (response.status < 200 || response.status >= 300) {
    throw new Error(`TVDB request failed (HTTP ${response.status || 0})`);
  }
  return includeEnvelope ? response.body : response.body?.data;
}

// Follow every page: using only page zero can silently lose later seasons.
async function fetchAllTvdbEpisodes(basePath) {
  const episodes = [];
  for (let page = 0; page < 500; page++) {
    const envelope = await authenticatedTvdbGet(`${basePath}${basePath.includes('?') ? '&' : '?'}page=${page}`, true);
    const rows = envelope?.data?.series?.episodes || envelope?.data?.episodes;
    if (!Array.isArray(rows)) throw new Error('TVDB returned an invalid episode catalogue');
    episodes.push(...rows);
    if (envelope.links?.next == null) return episodes;
    if (!rows.length) throw new Error('TVDB pagination returned an empty page with a next link');
  }
  throw new Error('TVDB episode catalogue exceeded the pagination limit');
}

function cachedTvdbGet(cache, key, path) {
  if (!cache.has(key)) {
    const request = authenticatedTvdbGet(path).catch(error => {
      cache.delete(key);
      throw error;
    });
    cache.set(key, request);
  }
  return cache.get(key);
}

async function fetchTvdbEpisodeList(seriesId, language = TVDB_EPISODE_LANGUAGE) {
  const normalizedLanguage = String(language || TVDB_EPISODE_LANGUAGE).trim().toLowerCase();
  const encodedSeriesId = encodeURIComponent(seriesId);
  const encodedLanguage = encodeURIComponent(normalizedLanguage);
  const cacheKey = `series:${seriesId}|seasonType:${TVDB_SEASON_TYPE}|language:${normalizedLanguage}|page:0`;
  const path = `/series/${encodedSeriesId}/episodes/${TVDB_SEASON_TYPE}/${encodedLanguage}`;
  if (!episodeListCache.has(cacheKey)) episodeListCache.set(cacheKey, fetchAllTvdbEpisodes(path).catch(error => { episodeListCache.delete(cacheKey); throw error; }));
  return episodeListCache.get(cacheKey);
}

async function fetchTvdbEpisodeTranslation(episodeId, language = TVDB_EPISODE_LANGUAGE) {
  const normalizedLanguage = String(language || TVDB_EPISODE_LANGUAGE).trim().toLowerCase();
  const cacheKey = `episode:${episodeId}|language:${normalizedLanguage}`;
  const path = `/episodes/${encodeURIComponent(episodeId)}/translations/${encodeURIComponent(normalizedLanguage)}`;
  return cachedTvdbGet(episodeTranslationCache, cacheKey, path);
}

async function fetchTvdbEpisodeBase(episodeId) {
  const cacheKey = `episode:${episodeId}|base`;
  const path = `/episodes/${encodeURIComponent(episodeId)}`;
  return cachedTvdbGet(episodeBaseCache, cacheKey, path);
}

async function fetchTvdbSeriesExtended(seriesId) {
  const encodedSeriesId = encodeURIComponent(seriesId);
  const cacheKey = `series:${seriesId}|extended`;
  const path = `/series/${encodedSeriesId}/extended`;
  return cachedTvdbGet(seriesExtendedCache, cacheKey, path);
}

async function fetchTvdbSeasonEpisodeList(seriesId, season) {
  const encodedSeriesId = encodeURIComponent(seriesId);
  const cacheKey = `series:${seriesId}|seasonType:${TVDB_SEASON_TYPE}|season:${season}|page:0`;
  const path = `/series/${encodedSeriesId}/episodes/${TVDB_SEASON_TYPE}?page=0&season=${encodeURIComponent(season)}`;
  const data = await cachedTvdbGet(episodeListCache, cacheKey, path);
  return data?.episodes || data?.series?.episodes || [];
}

function normalizeTitle(value) {
  return String(value || '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^\p{L}\p{N}]+/gu, ' ')
    .trim();
}

function isGenericEpisodeTitle(value) {
  const title = normalizeTitle(value);
  return /^(?:episode|aflevering|folge|episodio|episode|capitulo|chapter|part|deel)\s*(?:(?:no|number|nr)\s*)?\d+$/.test(title) ||
    /^(?:s\s*\d+\s*)?e\s*\d+$/.test(title);
}

function incrementReason(reasons, reason) {
  reasons[reason] = (reasons[reason] || 0) + 1;
}

function describeSkipReasons(reasons) {
  const labels = {
    genericTitle: 'generic titles',
    missingTitle: 'missing titles',
    duplicateProviderTitle: 'duplicate provider titles',
    noExactMatch: 'no exact normalized TVDB match',
    ambiguousTvdbTitle: 'ambiguous TVDB titles',
    reusedTvdbEpisode: 'TVDB episode already matched',
    missingAbsoluteNumber: 'titles without an absolute episode number',
    absoluteEpisodeNotFound: 'absolute TVDB episodes not found',
    ambiguousAbsoluteEpisode: 'ambiguous absolute TVDB episodes',
    invalidCanonicalEpisode: 'TVDB episodes without canonical default numbering',
  };
  return Object.entries(reasons)
    .map(([reason, count]) => `${labels[reason] || reason}: ${count}`)
    .join(', ');
}

function extractAbsoluteEpisodeNumber(value) {
  const match = /^(?:aflevering|episode)\s+(\d+)$/.exec(normalizeTitle(value));
  if (!match) return null;
  const number = Number(match[1]);
  return Number.isSafeInteger(number) && number > 0 ? number : null;
}

function extractEpisodeTitleNumber(value) {
  const match = /^(?:aflevering|episode)\s+(\d+)\b/.exec(normalizeTitle(value));
  if (!match) return null;
  const number = Number(match[1]);
  return Number.isSafeInteger(number) && number > 0 ? number : null;
}

function getOfficialSeasonNumbers(series) {
  const seasons = Array.isArray(series?.seasons) ? series.seasons : [];
  const official = seasons.filter(season => {
    const typeId = Number(season?.type?.id ?? season?.typeId);
    const type = normalizeTitle(season?.type?.type || season?.type?.name || season?.typeName);
    return typeId === 1 || type === 'official' || type === 'aired order' || type === 'default';
  });
  const selected = official.length ? official : seasons;
  return [...new Set(selected
    .map(season => Number(season?.number))
    .filter(number => Number.isInteger(number) && number > 0))]
    .sort((a, b) => a - b);
}

async function findGtstEpisodeByTitleNumber(tvdbSeriesId, absoluteNumber) {
  const series = await fetchTvdbSeriesExtended(tvdbSeriesId);
  const seasons = getOfficialSeasonNumbers(series);
  let low = 0;
  let high = seasons.length - 1;

  while (low <= high) {
    const middle = Math.floor((low + high) / 2);
    const season = seasons[middle];
    const episodes = await fetchTvdbSeasonEpisodeList(tvdbSeriesId, season);
    const numberedEpisodes = episodes
      .map(episode => ({ episode, titleNumber: extractEpisodeTitleNumber(episode?.name) }))
      .filter(entry => entry.titleNumber != null)
      .sort((a, b) => a.titleNumber - b.titleNumber);
    if (!numberedEpisodes.length) return [];

    const first = numberedEpisodes[0].titleNumber;
    const last = numberedEpisodes[numberedEpisodes.length - 1].titleNumber;
    if (absoluteNumber < first) {
      high = middle - 1;
      continue;
    }
    if (absoluteNumber > last) {
      low = middle + 1;
      continue;
    }
    return numberedEpisodes
      .filter(entry => entry.titleNumber === absoluteNumber)
      .map(entry => entry.episode);
  }
  return [];
}

async function fetchTvdbEpisodeTitles(episode, languages) {
  const titles = [String(episode?.name || '').trim()].filter(Boolean);
  for (const language of languages) {
    try {
      const translation = await fetchTvdbEpisodeTranslation(episode.id, language);
      const title = String(translation?.name || '').trim();
      if (title && !titles.some(existing => normalizeTitle(existing) === normalizeTitle(title))) titles.push(title);
    } catch (error) {
      console.warn('[TVDB] GTST episode translation request failed', {
        episodeId: episode.id,
        requestedLanguage: language,
        reason: error?.message || String(error),
      });
    }
  }
  return titles;
}

async function mapGtstAbsoluteTitleEpisodes(providerEpisodes, tvdbSeriesId, languages) {
  const mapping = new Map();
  const skipReasons = {};
  const usedTvdbIds = new Set();

  for (const providerEpisode of providerEpisodes) {
    const absoluteNumber = extractAbsoluteEpisodeNumber(providerEpisode.title);
    if (absoluteNumber == null) {
      incrementReason(skipReasons, 'missingAbsoluteNumber');
      continue;
    }

    const absoluteMatches = await findGtstEpisodeByTitleNumber(tvdbSeriesId, absoluteNumber);
    if (!absoluteMatches.length) {
      incrementReason(skipReasons, 'absoluteEpisodeNotFound');
      continue;
    }
    if (absoluteMatches.length !== 1) {
      incrementReason(skipReasons, 'ambiguousAbsoluteEpisode');
      continue;
    }

    const absoluteEpisode = absoluteMatches[0];
    if (absoluteEpisode?.id == null) {
      incrementReason(skipReasons, 'absoluteEpisodeNotFound');
      continue;
    }
    const canonicalEpisode = await fetchTvdbEpisodeBase(absoluteEpisode.id);
    const canonicalSeason = Number(canonicalEpisode?.seasonNumber);
    const canonicalNumber = Number(canonicalEpisode?.number);
    if (!Number.isInteger(canonicalSeason) || canonicalSeason < 1 ||
        !Number.isInteger(canonicalNumber) || canonicalNumber < 1) {
      incrementReason(skipReasons, 'invalidCanonicalEpisode');
      continue;
    }

    const titles = await fetchTvdbEpisodeTitles(
      { ...canonicalEpisode, name: absoluteEpisode.name || canonicalEpisode.name },
      languages,
    );
    const providerTitle = normalizeTitle(providerEpisode.title);
    const exactTitles = titles.filter(title =>
      extractAbsoluteEpisodeNumber(title) === absoluteNumber &&
      normalizeTitle(title) === providerTitle
    );
    if (!exactTitles.length) {
      incrementReason(skipReasons, 'noExactMatch');
      continue;
    }
    if (usedTvdbIds.has(String(canonicalEpisode.id))) {
      incrementReason(skipReasons, 'reusedTvdbEpisode');
      continue;
    }

    usedTvdbIds.add(String(canonicalEpisode.id));
    mapping.set(`${providerEpisode.season}|${providerEpisode.episode}`, {
      id: canonicalEpisode.id,
      season: canonicalSeason,
      episode: canonicalNumber,
      title: exactTitles[0],
    });
  }

  const matchStats = {
    matched: mapping.size,
    skipped: providerEpisodes.length - mapping.size,
    skipReasons,
  };
  const reasonSummary = describeSkipReasons(skipReasons);
  if (!mapping.size) {
    return {
      success: false,
      mapping,
      method: 'absolute-title',
      reason: `no reliable GTST absolute-number and exact-title mappings exist${reasonSummary ? ` (${reasonSummary})` : ''}`,
      matchStats,
    };
  }
  return {
    success: true,
    mapping,
    method: 'absolute-title',
    reason: `GTST absolute-number lookup with exact title verification; ${mapping.size} matched and ${matchStats.skipped} skipped${reasonSummary ? ` (${reasonSummary})` : ''}`,
    matchStats,
  };
}

function normalizeProviderEpisodes(episodes) {
  const unique = new Map();
  for (const episode of episodes || []) {
    const season = Number(episode.season);
    const number = Number(episode.episode);
    if (!Number.isInteger(season) || !Number.isInteger(number) || season < 0 || number < 1) continue;
    const key = episode.providerId ? `id:${episode.providerId}` : `number:${season}:${number}`;
    const normalized = {
      providerId: episode.providerId == null ? '' : String(episode.providerId),
      season,
      episode: number,
      title: String(episode.title || '').trim(),
      isSpecial: season === 0 || episode.isSpecial === true,
    };
    if (!unique.has(key)) unique.set(key, normalized);
    else if (!unique.get(key).title && normalized.title) unique.get(key).title = normalized.title;
  }
  return [...unique.values()].sort((a, b) => a.season - b.season || a.episode - b.episode);
}

function getDeclaredEpisodeNameLanguage(episode) {
  return String(episode?.nameLanguage || episode?.language || '').trim().toLowerCase();
}

function summarizeEpisodeNameLanguages(episodes) {
  const counts = {};
  for (const episode of episodes) {
    const language = episode._nameLanguage || 'unknown';
    counts[language] = (counts[language] || 0) + 1;
  }
  return counts;
}

async function ensureTvdbEpisodeNameLanguage(episodes, providerEpisodes, language) {
  const providerTitlesByNumber = new Map(providerEpisodes
    .map(episode => [`${episode.season}|${episode.episode}`, normalizeTitle(episode.title)])
    .filter(([, title]) => title));
  return Promise.all((episodes || []).map(async episode => {
    const returnedTitle = normalizeTitle(episode?.name);
    const declaredLanguage = getDeclaredEpisodeNameLanguage(episode);
    const correspondingProviderTitle = providerTitlesByNumber.get(`${episode?.seasonNumber}|${episode?.number}`);
    const contradictsProviderTitle = correspondingProviderTitle && returnedTitle !== correspondingProviderTitle;
    const returnedLanguage = declaredLanguage || language;
    const needsExplicitTranslation = episode?.id != null && (
      !returnedTitle ||
      (declaredLanguage && declaredLanguage !== language) ||
      contradictsProviderTitle
    );

    if (!needsExplicitTranslation) return { ...episode, _nameLanguage: returnedLanguage };

    try {
      const translation = await fetchTvdbEpisodeTranslation(episode.id, language);
      const translatedName = String(translation?.name || '').trim();
      if (translatedName) {
        return {
          ...episode,
          name: translatedName,
          _nameLanguage: String(translation?.language || language).trim().toLowerCase(),
        };
      }
    } catch (error) {
      console.warn('[TVDB] Explicit episode translation request failed', {
        episodeId: episode.id,
        requestedLanguage: language,
        endpointUrlShape: `${TVDB_BASE}/episodes/{episodeId}/translations/{language}`,
        reason: error?.message || String(error),
      });
    }
    return { ...episode, _nameLanguage: returnedLanguage };
  }));
}

function logTvdbEpisodeLanguageAudit(seriesId, language, receivedEpisodes, matchingEpisodes) {
  const matchingById = new Map((matchingEpisodes || []).map(episode => [String(episode.id), episode]));
  const titleResponse = {
    seriesId: String(seriesId),
    requestedLanguage: language,
    episodes: (receivedEpisodes || []).map(episode => {
      const matching = matchingById.get(String(episode.id)) || episode;
      return {
        id: episode.id,
        season: episode.seasonNumber,
        episode: episode.number,
        receivedTitle: String(episode.name || '').trim(),
        receivedLanguage: getDeclaredEpisodeNameLanguage(episode) || 'unknown',
        matchingTitle: String(matching.name || '').trim(),
        matchingLanguage: String(matching._nameLanguage || getDeclaredEpisodeNameLanguage(matching) || language).trim().toLowerCase(),
      };
    }),
  };
  console.info('[TVDB] Series episode language audit', {
    seriesId: String(seriesId),
    requestedLanguage: language,
    endpointUrlShape: TVDB_EPISODE_ENDPOINT_SHAPE,
    returnedEpisodeNameLanguages: summarizeEpisodeNameLanguages(matchingEpisodes),
  });
  console.info('[TVDB] Series episode title response', titleResponse);
  console.info('[TVDB] Series episode title response JSON', JSON.stringify(titleResponse));
}

function logTvdbEpisodeMatchTitles(seriesId, providerEpisodes, episodes) {
  const matchingInput = {
    seriesId: String(seriesId),
    providerEpisodes: providerEpisodes.map(episode => ({
      providerId: episode.providerId,
      season: episode.season,
      episode: episode.episode,
      title: episode.title,
    })),
    tvdbEpisodes: episodes.map(episode => ({
      id: episode.id,
      season: episode.season,
      episode: episode.episode,
      titles: [episode.title, ...(episode.alternateTitles || [])].filter(Boolean),
    })),
  };
  console.info('[TVDB] Episode titles available for matching', matchingInput);
  console.info('[TVDB] Title matching input JSON', JSON.stringify(matchingInput));
}

function cleanTvdbEpisodes(episodes) {
  const unique = new Map();
  let specialsExcluded = 0;
  for (const episode of episodes || []) {
    const season = Number(episode.seasonNumber);
    const number = Number(episode.number);
    if (season === 0) {
      specialsExcluded++;
      continue;
    }
    if (!Number.isInteger(season) || !Number.isInteger(number) || season < 1 || number < 1 || episode.id == null) continue;
    if (!unique.has(String(episode.id))) unique.set(String(episode.id), {
      id: episode.id,
      season,
      episode: number,
      title: String(episode.name || '').trim(),
    });
  }
  return {
    episodes: [...unique.values()].sort((a, b) => a.season - b.season || a.episode - b.episode),
    specialsExcluded,
  };
}

function mergeTvdbEpisodeTitles(primaryCatalog, alternateCatalogs) {
  const byId = new Map(primaryCatalog.episodes.map(episode => [String(episode.id), episode]));
  const byNumber = new Map(primaryCatalog.episodes.map(episode => [`${episode.season}|${episode.episode}`, episode]));
  for (const catalog of alternateCatalogs) {
    for (const alternate of catalog.episodes) {
      const target = byId.get(String(alternate.id)) || byNumber.get(`${alternate.season}|${alternate.episode}`);
      const title = String(alternate.title || '').trim();
      if (!target || !title || normalizeTitle(title) === normalizeTitle(target.title)) continue;
      target.alternateTitles ||= [];
      if (!target.alternateTitles.some(existing => normalizeTitle(existing) === normalizeTitle(title))) {
        target.alternateTitles.push(title);
      }
    }
  }
  return primaryCatalog;
}

function findDuplicateNumber(episodes) {
  const seen = new Set();
  for (const episode of episodes) {
    const key = `${episode.season}|${episode.episode}`;
    if (seen.has(key)) return key;
    seen.add(key);
  }
  return null;
}

function mapEpisodes(providerEpisodes, tvdbEpisodes, { requireTitleMatch = false } = {}) {
  const mapping = new Map();
  if (!requireTitleMatch && providerEpisodes.length === tvdbEpisodes.length) {
    providerEpisodes.forEach((episode, index) => mapping.set(`${episode.season}|${episode.episode}`, tvdbEpisodes[index]));
    return {
      success: true,
      mapping,
      method: 'order',
      reason: 'regular-episode counts match',
      matchStats: { matched: providerEpisodes.length, skipped: 0, skipReasons: {} },
    };
  }

  const providerTitleCounts = new Map();
  for (const episode of providerEpisodes) {
    const title = normalizeTitle(episode.title);
    if (title) providerTitleCounts.set(title, (providerTitleCounts.get(title) || 0) + 1);
  }

  const tvdbByTitle = new Map();
  for (const episode of tvdbEpisodes) {
    const titles = new Set([episode.title, ...(episode.alternateTitles || [])]
      .map(normalizeTitle)
      .filter(Boolean));
    for (const title of titles) {
      if (!tvdbByTitle.has(title)) tvdbByTitle.set(title, []);
      tvdbByTitle.get(title).push(episode);
    }
  }

  const skipReasons = {};
  const usedTvdbIds = new Set();
  for (const providerEpisode of providerEpisodes) {
    const title = normalizeTitle(providerEpisode.title);
    if (!title) {
      incrementReason(skipReasons, 'missingTitle');
      continue;
    }
    if (isGenericEpisodeTitle(title)) {
      incrementReason(skipReasons, 'genericTitle');
      continue;
    }
    if (providerTitleCounts.get(title) !== 1) {
      incrementReason(skipReasons, 'duplicateProviderTitle');
      continue;
    }

    const exact = tvdbByTitle.get(title) || [];
    if (!exact.length) {
      incrementReason(skipReasons, 'noExactMatch');
      continue;
    }
    if (exact.length !== 1) {
      incrementReason(skipReasons, 'ambiguousTvdbTitle');
      continue;
    }

    const match = exact[0];
    if (usedTvdbIds.has(String(match.id))) {
      incrementReason(skipReasons, 'reusedTvdbEpisode');
      continue;
    }
    usedTvdbIds.add(String(match.id));
    mapping.set(`${providerEpisode.season}|${providerEpisode.episode}`, match);
  }

  const matchStats = {
    matched: mapping.size,
    skipped: providerEpisodes.length - mapping.size,
    skipReasons,
  };
  const reasonSummary = describeSkipReasons(skipReasons);
  if (!mapping.size) {
    return {
      success: false,
      mapping,
      method: 'title',
      reason: `regular-episode counts differ and no reliable exact title mappings exist${reasonSummary ? ` (${reasonSummary})` : ''}`,
      matchStats,
    };
  }
  return {
    success: true,
    mapping,
    method: 'title',
    reason: `regular-episode counts differ; ${mapping.size} matched and ${matchStats.skipped} skipped${reasonSummary ? ` (${reasonSummary})` : ''}`,
    matchStats,
  };
}

async function resolveTvdbSeriesId(imdbId) {
  const results = await authenticatedTvdbGet(`/search/remoteid/${encodeURIComponent(imdbId)}`);
  const ids = [...new Set((Array.isArray(results) ? results : [])
    .map(result => result?.series?.id)
    .filter(id => id != null)
    .map(String))];
  if (!ids.length) throw new Error('no TVDB series matched the IMDb ID');
  if (ids.length !== 1) throw new Error('the IMDb ID matched multiple TVDB series');
  return ids[0];
}

/**
 * Return export/submission-safe items whose season/episode metadata is canonical TVDB data.
 * Count mismatches may return a partial, reliable title mapping. A failure means
 * that no regular provider episode could be mapped safely for the series.
 */
async function mapSeriesItemsToTvdb(items, providerCatalog) {
  if (!items.length) return { success: true, items: [], method: 'none' };
  const imdbId = items[0].imdb_id;
  const catalog = normalizeProviderEpisodes(providerCatalog);
  const providerSpecialKeys = new Set(catalog
    .filter(episode => episode.isSpecial)
    .map(episode => `${episode.season}|${episode.episode}`));
  const regularItems = items.filter(item => {
    const season = Number(item.season);
    return Number.isInteger(season) && season > 0 && !providerSpecialKeys.has(`${item.season}|${item.episode}`);
  });
  const capturedSpecialsExcluded = items.length - regularItems.length;
  if (!regularItems.length) {
    const providerSpecialsExcluded = catalog.filter(episode => episode.isSpecial).length;
    return {
      success: true,
      items: [],
      method: 'specials-only',
      reason: 'all captured segments belong to provider specials',
      stats: { providerRegular: 0, tvdbRegular: 0, providerSpecialsExcluded, tvdbSpecialsExcluded: 0, capturedSpecialsExcluded },
    };
  }

  const providerEpisodes = catalog.filter(episode => !episode.isSpecial);
  const providerSpecialsExcluded = catalog.length - providerEpisodes.length;
  if (!providerEpisodes.length) {
    return { success: false, reason: 'provider regular-episode metadata is unavailable' };
  }
  const duplicateProviderNumber = findDuplicateNumber(providerEpisodes);
  if (duplicateProviderNumber) {
    return { success: false, reason: `provider metadata has duplicate regular episode number ${duplicateProviderNumber.replace('|', 'x')}` };
  }
  try {
    const tvdbSeriesId = await resolveTvdbSeriesId(imdbId);
    const requireTitleMatch = regularItems.every(item => item._tvdbRequireTitleMatch === true);
    const episodeLanguages = [...new Set(items.flatMap(item =>
      Array.isArray(item._tvdbEpisodeLanguages) ? item._tvdbEpisodeLanguages : []
    ).map(language => String(language || '').trim().toLowerCase()))]
      .filter(Boolean);
    // GTST always uses absolute numbering, including captures restored from older releases.
    const useGtstAbsoluteTitleMatch = imdbId === GTST_IMDB_ID;

    let result;
    let tvdbEpisodes = [];
    let tvdbSpecialsExcluded = 0;
    if (useGtstAbsoluteTitleMatch) {
      result = await mapGtstAbsoluteTitleEpisodes(
        providerEpisodes,
        tvdbSeriesId,
        [...new Set([TVDB_EPISODE_LANGUAGE, ...episodeLanguages])],
      );
    } else {
      const episodeList = await fetchTvdbEpisodeList(tvdbSeriesId, TVDB_EPISODE_LANGUAGE);
      const localizedEpisodes = await ensureTvdbEpisodeNameLanguage(episodeList, providerEpisodes, TVDB_EPISODE_LANGUAGE);
      logTvdbEpisodeLanguageAudit(tvdbSeriesId, TVDB_EPISODE_LANGUAGE, episodeList, localizedEpisodes);
      const tvdbCatalog = cleanTvdbEpisodes(localizedEpisodes);
      tvdbEpisodes = tvdbCatalog.episodes;
      tvdbSpecialsExcluded = tvdbCatalog.specialsExcluded;
      if (requireTitleMatch || providerEpisodes.length !== tvdbEpisodes.length) {
        const additionalLanguages = episodeLanguages
          .filter(language => language !== TVDB_EPISODE_LANGUAGE);
        const alternateCatalogs = [];
        for (const language of additionalLanguages) {
          const alternateList = await fetchTvdbEpisodeList(tvdbSeriesId, language);
          const alternateLocalized = await ensureTvdbEpisodeNameLanguage(alternateList, providerEpisodes, language);
          logTvdbEpisodeLanguageAudit(tvdbSeriesId, language, alternateList, alternateLocalized);
          alternateCatalogs.push(cleanTvdbEpisodes(alternateLocalized));
        }
        mergeTvdbEpisodeTitles(tvdbCatalog, alternateCatalogs);
      }
      logTvdbEpisodeMatchTitles(tvdbSeriesId, providerEpisodes, tvdbEpisodes);
      if (!tvdbEpisodes.length) return { success: false, reason: 'TVDB returned no usable episode metadata' };
      const duplicateTvdbNumber = findDuplicateNumber(tvdbEpisodes);
      if (duplicateTvdbNumber) {
        return { success: false, reason: `TVDB metadata has duplicate regular episode number ${duplicateTvdbNumber.replace('|', 'x')}` };
      }
      result = mapEpisodes(providerEpisodes, tvdbEpisodes, { requireTitleMatch });
    }
    const stats = {
      providerRegular: providerEpisodes.length,
      tvdbRegular: useGtstAbsoluteTitleMatch ? result.matchStats?.matched ?? 0 : tvdbEpisodes.length,
      providerSpecialsExcluded,
      tvdbSpecialsExcluded,
      capturedSpecialsExcluded,
      regularEpisodesMatched: result.matchStats?.matched ?? 0,
      regularEpisodesSkipped: result.matchStats?.skipped ?? providerEpisodes.length,
      regularEpisodeSkipReasons: result.matchStats?.skipReasons || {},
    };
    if (!result.success) return { ...result, stats };

    const mappedItems = [];
    for (const item of regularItems) {
      const match = result.mapping.get(`${item.season}|${item.episode}`);
      if (!match) continue;
      const {
        _eid,
        _episodeTitle,
        _showId,
        _tvdbEpisodeLanguages,
        _tvdbRequireTitleMatch,
        _tvdbAbsoluteTitleMatch,
        ...submissionItem
      } = item;
      mappedItems.push({ ...submissionItem, season: match.season, episode: match.episode });
    }
    stats.capturedRegularSegmentsMatched = mappedItems.length;
    stats.capturedRegularSegmentsSkipped = regularItems.length - mappedItems.length;
    return { success: true, items: mappedItems, method: result.method, reason: result.reason, tvdbSeriesId, stats };
  } catch (error) {
    return { success: false, reason: error?.message || 'TVDB mapping failed' };
  }
}

function setProviderEpisodeCatalog(episodes, showId = state.showId) {
  const normalized = normalizeProviderEpisodes(episodes);
  const normalizedShowId = showId != null ? String(showId) : '';
  if (!normalizedShowId || normalizedShowId === state.showId) state.providerEpisodes = normalized;
  if (normalizedShowId) {
    state.providerEpisodesByShowId ||= {};
    state.providerEpisodesByShowId[normalizedShowId] = normalized;
  }
}

function recordProviderEpisode(episode, showId = state.showId) {
  const normalizedShowId = showId != null ? String(showId) : '';
  const previous = normalizedShowId
    ? state.providerEpisodesByShowId?.[normalizedShowId] || []
    : state.providerEpisodes || [];
  const current = normalizeProviderEpisodes([...previous, episode]);
  if (!normalizedShowId || normalizedShowId === state.showId) state.providerEpisodes = current;
  if (normalizedShowId) {
    state.providerEpisodesByShowId ||= {};
    state.providerEpisodesByShowId[normalizedShowId] = current;
  }
}

return { loadTvdbSettings, saveTvdbSettings, mapSeriesItemsToTvdb, setProviderEpisodeCatalog, recordProviderEpisode };
})();
const tmdb = (() => {
/** TMDB presence checks. Credentials stay in userscript storage, outside public state. */
const TMDB_TOKEN_STORAGE = 'segmentScraper.tmdb.token';
const tmdbSceneCache = new Map();

function saveTmdbToken(value) {
  if (typeof GM_setValue !== 'function') return false;
  try {
    GM_setValue(TMDB_TOKEN_STORAGE, String(value || '').trim().replace(/^Bearer\s+/i, ''));
    tmdbSceneCache.clear();
    return true;
  } catch (_) { return false; }
}

function tmdbRequest(path, token) {
  return new Promise(resolve => {
    const xhr = (typeof GM_xmlhttpRequest === 'function' && GM_xmlhttpRequest)
      || (typeof GM !== 'undefined' && GM.xmlHttpRequest);
    if (!xhr) { resolve(null); return; }
    try {
      xhr({ method: 'GET', url: `https://api.themoviedb.org/3${path}`,
        headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' }, timeout: 10000,
        onload: response => {
          try { resolve(response.status === 200 ? JSON.parse(response.responseText) : null); }
          catch (_) { resolve(null); }
        }, onerror: () => resolve(null), ontimeout: () => resolve(null), onabort: () => resolve(null),
      });
    } catch (_) { resolve(null); }
  });
}

async function checkTmdbExtraScenes(imdbId) {
  if (!/^tt\d+$/.test(String(imdbId))) return { status: 'unavailable', reason: 'Invalid IMDb ID' };
  let token = '';
  try { token = typeof GM_getValue === 'function' ? String(GM_getValue(TMDB_TOKEN_STORAGE, '') || '').trim() : ''; }
  catch (_) {}
  if (!token) return { status: 'unavailable', reason: 'Save your TMDB API Read Access Token first' };
  const cached = tmdbSceneCache.get(imdbId);
  if (cached && cached.expires > Date.now()) return cached.result;
  const found = await tmdbRequest(`/find/${encodeURIComponent(imdbId)}?external_source=imdb_id`, token);
  if (!Array.isArray(found?.movie_results) || found.movie_results.length !== 1
    || !Number.isInteger(found.movie_results[0]?.id) || found.movie_results[0].id <= 0) {
    return { status: 'unavailable', reason: 'TMDB movie lookup failed or was ambiguous' };
  }
  const tmdbId = found.movie_results[0].id;
  const data = await tmdbRequest(`/movie/${tmdbId}/keywords`, token);
  if (!Array.isArray(data?.keywords) || data.keywords.some(keyword => typeof keyword?.name !== 'string')) {
    return { status: 'unavailable', reason: 'TMDB keyword check failed; verify token or retry' };
  }
  const keywords = data.keywords.map(keyword => String(keyword?.name || '').trim().toLowerCase())
    .filter(name => ['aftercreditsstinger', 'duringcreditsstinger'].includes(name));
  const result = { status: keywords.length ? 'present' : 'unknown', tmdbId, keywords };
  if (tmdbSceneCache.size >= 200) tmdbSceneCache.delete(tmdbSceneCache.keys().next().value);
  tmdbSceneCache.set(imdbId, { result, expires: Date.now() + 15 * 60 * 1000 });
  return result;
}

return { saveTmdbToken, checkTmdbExtraScenes };
})();
const update_check = (() => {
/**
 * Required-update check for the generated userscript.
 * The version and install URL are injected by the bundler from package.json.
 */


const VERSION_CHECK_TIMEOUT_MS = 8000;
let updateCheckPromise = null;

function parseVersion(version) {
  const match = String(version || '').trim().match(/^v?(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?$/);
  if (!match) return null;
  return {
    numbers: match.slice(1, 4).map(Number),
    prerelease: match[4] ? match[4].split('.') : [],
  };
}

function comparePrerelease(left, right) {
  if (!left.length && !right.length) return 0;
  if (!left.length) return 1;
  if (!right.length) return -1;

  const length = Math.max(left.length, right.length);
  for (let index = 0; index < length; index++) {
    if (left[index] === undefined) return -1;
    if (right[index] === undefined) return 1;
    if (left[index] === right[index]) continue;

    const leftNumeric = /^\d+$/.test(left[index]);
    const rightNumeric = /^\d+$/.test(right[index]);
    if (leftNumeric && rightNumeric) return Number(left[index]) > Number(right[index]) ? 1 : -1;
    if (leftNumeric !== rightNumeric) return leftNumeric ? -1 : 1;
    return left[index] > right[index] ? 1 : -1;
  }
  return 0;
}

/** Compare two semantic versions. Returns 1 when left is newer, -1 when older. */
function compareVersions(leftVersion, rightVersion) {
  const left = parseVersion(leftVersion);
  const right = parseVersion(rightVersion);
  if (!left || !right) return null;

  for (let index = 0; index < 3; index++) {
    if (left.numbers[index] === right.numbers[index]) continue;
    return left.numbers[index] > right.numbers[index] ? 1 : -1;
  }
  return comparePrerelease(left.prerelease, right.prerelease);
}

/** Read the userscript version from its metadata header. */
function extractUserscriptVersion(source) {
  return String(source || '').match(/^\s*\/\/\s*@version\s+([^\s]+)\s*$/m)?.[1] || null;
}

function requestRemoteUserscript(request) {
  return new Promise((resolve, reject) => {
    request({
      method: 'GET',
      url: `${SEGMENTSCRAPER_UPDATE_URL}?update-check=${Date.now()}`,
      timeout: VERSION_CHECK_TIMEOUT_MS,
      headers: { 'Cache-Control': 'no-cache' },
      onload: response => {
        if (response.status < 200 || response.status >= 300) {
          reject(new Error(`GitHub returned HTTP ${response.status}`));
          return;
        }
        resolve(response.responseText);
      },
      onerror: () => reject(new Error('GitHub request failed')),
      ontimeout: () => reject(new Error('GitHub request timed out')),
    });
  });
}

/**
 * Check GitHub once per page load. A failed check is fail-open; a confirmed newer
 * version is fail-closed and must be installed before normal use continues.
 */
function checkForRequiredUpdate(request = _GM_xmlhttpRequest) {
  if (updateCheckPromise) return updateCheckPromise;

  state.updateStatus = 'checking';
  state.currentVersion = SEGMENTSCRAPER_VERSION;
  state.updateUrl = SEGMENTSCRAPER_UPDATE_URL;

  updateCheckPromise = (async () => {
    if (typeof request !== 'function') {
      state.updateStatus = 'unavailable';
      return { required: false, status: state.updateStatus };
    }

    try {
      const source = await requestRemoteUserscript(request);
      const latestVersion = extractUserscriptVersion(source);
      const comparison = compareVersions(latestVersion, SEGMENTSCRAPER_VERSION);
      if (!latestVersion || comparison === null) throw new Error('GitHub version is invalid');

      state.latestVersion = latestVersion;
      state.updateRequired = comparison > 0;
      state.updateStatus = state.updateRequired ? 'required' : 'current';
      return { required: state.updateRequired, status: state.updateStatus, latestVersion };
    } catch (error) {
      state.updateStatus = 'unavailable';
      console.warn('[NFE] Update check unavailable; continuing with the installed version.', error);
      return { required: false, status: state.updateStatus, error };
    }
  })();

  return updateCheckPromise;
}

return { compareVersions, extractUserscriptVersion, checkForRequiredUpdate };
})();
return { ...output_policy, ...network, ...tvdb, ...tmdb, ...update_check };
}
